ALTER TABLE ITEM DROP FOREIGN KEY FK_ITEM_OWNER_USERID
ALTER TABLE USER_ITEM DROP FOREIGN KEY FK_USER_ITEM_User_USERID
ALTER TABLE USER_ITEM DROP FOREIGN KEY FK_USER_ITEM_Items_ITEMID
DROP TABLE ITEM
DROP TABLE USER
DROP TABLE USER_ITEM
